---
name: site
version: 0.0.0
executables:
  site:
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - hakyll
      - filepath
      - blaze-markup
      - skylighting
      - text
      - xml-conduit
