---
name: site
version: 0.0.0

dependencies:
  - base
  - hakyll

library:
  source-dirs: src
  dependencies:
    - containers
    - filepath

executables:
  site:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - site
      - blaze-markup
      - skylighting
      - text
      - xml-conduit
