---
version: 2.0

jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Digest
          command: |
            md5sum stack.yaml package.yaml Main.hs > digest
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum "digest" }}
            - v1-{{ .Branch }}-
            - v1-master-
      - run:
          name: Dependencies
          command: |
            apt-get update
            apt-get install python-pip
            pip install s3cmd
            curl -sSL https://get.haskellstack.org/ | sh
            make setup
      - run:
          name: Build
          command: make build
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "digest" }}
          paths:
            - ~/.cache/pip
            - ~/.stack
            - ./.stack-work
      - run:
          name: Lint
          command: make lint
      - run:
          name: Site
          command: make clean site
      - run:
          name: Publish (dry-run)
          command: make publish S3CMD='s3cmd --dry-run'
      - run:
          name: Publish (if master)
          command: |
            if [ "$CIRCLE_BRANCH" = master ]; then
              # TODO: remove safe-guard
              echo make publish
            fi
