name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            ./.stack-work
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('stack.yaml') }}-
            ${{ runner.os }}-

      - name: Build
        run: |
          stack --no-terminal build --pedantic

      - name: Lint
        run: |
          stack --no-terminal install --copy-compiler-tool hlint
          stack --no-terminal exec hlint Main.hs

      - name: Site
        run: |
          stack --no-terminal exec site build

      - name: Diff
        run: |
          mkdir -p _released
          aws s3 sync --delete s3://pbrisbin.com _released
          diff --unified _released _site
        continue-on-error: true

      - name: Deploy
        if: endsWith(github.ref, '/main')
        uses: reggionick/s3-deploy@v3
        with:
          folder: _site
          bucket: pbrisbin.com
          bucket-region: us-east-1
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: '/*'
          delete-removed: true
